version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
    networks:
      - es-net
    ports:
      - 9200:9200
    volumes:
      - data01:/home/siddharthdixit/elastic/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2548M
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 768M 
  
volumes:
  data01:
    driver: local
    
networks:
  es-net:
    driver: bridge
